import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage {
  english('en', 'English (English)', 'English'),
  hindi('hi', 'Hindi (हिंदी)', 'हिन्दी'),
  marathi('mr', 'Marathi (मराठी)', 'मराठी'),
  gujarati('gu', 'Gujarati (ગુજરાતી)', 'ગુજરાતી');

  final String code;
  final String displayName;
  final String nativeName;

  const AppLanguage(this.code, this.displayName, this.nativeName);

  static AppLanguage fromCode(String code) {
    return AppLanguage.values.firstWhere(
      (lang) => lang.code == code,
      orElse: () => AppLanguage.english,
    );
  }
}

class LanguageProvider extends ChangeNotifier {
  static const String _prefKey = 'selected_app_language_code';
  AppLanguage _currentLanguage = AppLanguage.english;

  AppLanguage get currentLanguage => _currentLanguage;
  Locale get currentLocale => Locale(_currentLanguage.code);

  LanguageProvider() {
    _loadSavedLanguage();
  }

  Future<void> _loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString(_prefKey);
    if (savedCode != null) {
      _currentLanguage = AppLanguage.fromCode(savedCode);
      notifyListeners();
    }
  }

  Future<void> setLanguage(AppLanguage language) async {
    if (_currentLanguage == language) return;
    _currentLanguage = language;
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, language.code);
  }

  String translate(String key) {
    final langMap = AppStrings.translations[_currentLanguage.code] ?? AppStrings.translations['en']!;
    return langMap[key] ?? AppStrings.translations['en']?[key] ?? key;
  }

  /// Translates produce/crop names, quantities, prices, categories, dynamic text, and units
  String translateProduce(String text) {
    if (_currentLanguage == AppLanguage.english) return text;
    final langMap = AppStrings.translations[_currentLanguage.code] ?? AppStrings.translations['en']!;

    if (langMap.containsKey(text)) {
      return langMap[text]!;
    }

    String result = text;
    // Replace units and dynamic phrases
    final replacements = {
      ' / Kg': ' / ${langMap['unit_kg'] ?? 'Kg'}',
      ' / Qtl': ' / ${langMap['unit_qtl'] ?? 'Qtl'}',
      ' Kg': ' ${langMap['unit_kg'] ?? 'Kg'}',
      ' Acres': ' ${langMap['unit_acres'] ?? 'Acres'}',
      ' Acre': ' ${langMap['unit_acres'] ?? 'Acre'}',
      'Active': langMap['status_active'] ?? 'Active',
      'Inactive': langMap['status_inactive'] ?? 'Inactive',
      'Under Inspection': langMap['status_under_inspection'] ?? 'Under Inspection',
      'Quality Verified': langMap['status_quality_verified'] ?? 'Quality Verified',
      'Sold to Warehouse': langMap['status_sold_warehouse'] ?? 'Sold to Warehouse',
      'Completed': langMap['completed'] ?? 'Completed',
      'In Processing': langMap['in_processing'] ?? 'In Processing',
      'New': langMap['new_orders'] ?? 'New',
    };

    replacements.forEach((k, v) {
      if (result.contains(k)) {
        result = result.replaceAll(k, v);
      }
    });

    final englishMap = AppStrings.translations['en']!;
    englishMap.forEach((k, v) {
      if (v.isNotEmpty && langMap.containsKey(k)) {
        final translatedVal = langMap[k]!;
        if (result.contains(v)) {
          result = result.replaceAll(v, translatedVal);
        }
      }
    });

    return result;
  }
}

class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      // Nav & Common
      'nav_home': 'Home',
      'nav_products': 'My Products',
      'nav_orders': 'Orders',
      'nav_wallet': 'Wallet',
      'nav_profile': 'Profile',
      'app_title': 'Kisan Sathi',

      // Units
      'unit_kg': 'Kg',
      'unit_qtl': 'Qtl',
      'unit_ton': 'Ton',
      'unit_acres': 'Acres',

      // Farmer Persona & Locations
      'farmer_name': 'Rameshwar Singh',
      'default_location': 'Sehore, Madhya Pradesh',
      'location_sehore': 'Sehore, Madhya Pradesh',
      'location_mp': 'Madhya Pradesh',

      // Farm Details & Insurance
      'kharif_rabi_badge': 'Kharif & Rabi',
      'val_registered_land': '4.5 Acres (Black Soil)',
      'val_kcc_limit': 'Active (Limit ₹3,00,000)',
      'val_crop_insurance': 'Insured (Rabi 2026)',
      'val_primary_crops': 'Wheat, Soyabean, Tomatoes',
      'val_bank_sbi': 'State Bank of India (SBI)',
      'val_aadhaar_status': 'Verified with UIDAI',
      'val_total_land_loc': '4.5 Acres (Sehore)',
      'val_pm_kisan_status': 'Linked & Active',
      'val_village': 'Ashta Gram, Sehore',
      'val_district_state': 'Sehore, MP - 466116',
      'val_nearest_mandi': 'Sehore APMC Main Yard (4 Km)',

      // Categories
      'category_grains': 'Grains',
      'category_fruits': 'Fruits',
      'category_vegetables': 'Vegetables',
      'category_pulses': 'Pulses',
      'category_pulses_lentils': 'Pulses & Lentils',
      'category_oilseeds': 'Oilseeds',
      'category_spices': 'Spices',
      'category_organic': 'Organic Produce',

      'Grains': 'Grains',
      'Fruits': 'Fruits',
      'Vegetables': 'Vegetables',
      'Pulses': 'Pulses',
      'Pulses & Lentils': 'Pulses & Lentils',
      'Oilseeds': 'Oilseeds',
      'Spices': 'Spices',
      'Organic Produce': 'Organic Produce',

      // Specific Crops & Produce
      'Wheat (Local Quality)': 'Wheat (Local Quality)',
      'Sharbati Wheat': 'Sharbati Wheat',
      'Wheat': 'Wheat',
      'Tomatoes': 'Tomatoes',
      'Fresh Tomatoes': 'Fresh Tomatoes',
      'Potatoes': 'Potatoes',
      'Chana Dal': 'Chana Dal',
      'Desi Chickpeas': 'Desi Chickpeas',
      'Yellow Soyabean': 'Yellow Soyabean',
      'Soyabean': 'Soyabean',
      'Mustard Seeds': 'Mustard Seeds',
      'Fresh Apples': 'Fresh Apples',
      'Apples': 'Apples',
      'Onions': 'Onions',
      'Rice (Basmati)': 'Rice (Basmati)',
      'Rice': 'Rice',
      'Cotton (Kapas)': 'Cotton (Kapas)',
      'Garlic': 'Garlic',
      'Ginger': 'Ginger',

      // Buyers
      'buyer_ramesh_kirana': 'Ramesh Kirana Store, Indore',
      'buyer_shri_shyam': 'Shri Shyam Traders, Bhopal',
      'buyer_krishi_mandi': 'Krishi Mandi, Ujjain',
      'buyer_sahyadri_fpo': 'Sahyadri Farmers Producer Co.',

      // Home Screen
      'greeting': 'Hello Farmer!',
      'sell_produce_title': 'Sell Your Produce',
      'sell_produce_sub': 'Directly to Buyers',
      'add_product_btn': 'Add Product',
      'total_products': 'Total Products',
      'total_orders': 'Total Orders',
      'total_sales': 'Total Sales',
      'today_overview': "Today's Overview",
      'new_orders': 'New Orders',
      'in_processing': 'In Processing',
      'completed': 'Completed',
      'live_mandi_rates': 'Live Mandi Rates',
      'view_all': 'View All',
      'live_badge': 'Live',

      // Profile Screen
      'my_profile': 'My Profile',
      'personal_info': 'Personal Information',
      'bank_details': 'Bank Details',
      'address_farm_loc': 'Address & Farm Location',
      'sales_mandi_reports': 'Sales & Mandi Reports',
      'language': 'Language',
      'help_support': 'Help & Support',
      'log_out': 'Log Out',
      'logout_confirm_title': 'Log Out?',
      'logout_confirm_desc': 'Are you sure you want to log out of your Kisan account?',
      'cancel': 'Cancel',
      'agri_land_insurance': 'Agricultural Land & Insurance',
      'registered_land': 'Registered Land Holding',
      'kcc': 'Kisan Credit Card (KCC)',
      'crop_insurance': 'PM Fasal Bima (Insurance)',
      'primary_crops': 'Primary Commodities',
      'govt_footer_1': 'Kisan Sathi App v2.4.0 • Govt of India Agro Portal',
      'govt_footer_2': 'Secured with Aadhaar e-KYC & DBT Direct Payouts 🔒',
      'select_language': 'Select Language (भाषा चुनें)',
      'update_profile_photo': 'Update Profile Photo',
      'take_camera_photo': 'Take Camera Selfie',
      'choose_gallery': 'Choose from Gallery',
      'detect_gps_btn': 'Detect Live Farm GPS Location',
      'tap_to_call': 'Tap to Call',

      // My Products Screen
      'my_products_title': 'My Products',
      'inventory_overview': 'Inventory Overview',
      'listed_produce': 'Listed Produce',
      'active_stock': 'Active Stock',
      'total_worth': 'Total Worth',
      'items_count': 'Items',
      'crops_count': 'Crops',
      'all_filter': 'All',
      'active_filter': 'Active',
      'inactive_filter': 'Inactive',
      'grade_a': 'Grade A',
      'grade_standard': 'Standard',
      'grade_organic': 'Organic',
      'status_active': 'Active',
      'status_inactive': 'Inactive',
      'total_prefix': 'Total:',

      // Orders Screen
      'my_orders_title': 'My Orders',
      'filter_all': 'All',
      'filter_new': 'New',
      'filter_processing': 'In Processing',
      'filter_completed': 'Completed',
      'order_id': 'Order ID',
      'view_details': 'View Details',
      'order_details': 'Order Details',
      'buyer_info': 'Buyer Information',
      'product_details': 'Product Details',
      'order_timeline': 'Order Progress Timeline',
      'accept_order': 'Accept Order',
      'decline_order': 'Decline Order',
      'order_accepted_splash_title': 'Order Accepted!',
      'order_accepted_splash_subtitle': 'Packaging for delivery has started. Prepare your produce for shipment.',
      'packaging_in_progress': 'Packaging for Delivery in Progress',
      'order_delivered_splash_title': 'Delivery Completed!',
      'order_delivered_splash_subtitle': 'Order successfully delivered to buyer! Payment has been credited to your wallet balance.',
      'payment_credited_to_wallet': 'Payment Credited to Wallet',
      'continue_to_orders': 'Back to My Orders',
      'view_order_details': 'View Order Details',
      'order_splash_done': 'Done',

      // Wallet Screen
      'my_wallet': 'My Wallet',
      'total_balance': 'Total Balance',
      'withdraw_btn': 'Withdraw',
      'withdraw_to_bank': 'Withdraw to Bank',
      'earned_this_month': 'Earned This Month',
      'withdrawn': 'Withdrawn',
      'transfer_fee': 'Instant IMPS (Zero Fee)',
      'recent_transactions': 'Recent Transactions',
      'linked_bank': 'Linked Bank Account (DBT Verified)',
      'linked_bank_accounts': 'Linked Bank Accounts',
      'add_bank_account': 'Add Bank Account',
      'account_holder_name': 'Account Holder Name',
      'select_bank': 'Select Bank',
      'account_number': 'Account Number',
      'confirm_account_number': 'Re-enter Account Number',
      'ifsc_code': 'IFSC Code',
      'account_type': 'Account Type',
      'verify_and_link': 'Verify & Link Bank Account',
      'view_sales_analytics': 'View Sales & Mandi Analytics',

      // Add Product Screen
      'add_new_product': 'Add New Product',
      'crop_photo': 'Crop Photo',
      'product_name': 'Product Name',
      'category': 'Category',
      'quality_grade': 'Quality Grade',
      'description_optional': 'Description (Optional)',
      'publish_product': 'Publish Product to Mandi',

      // Produce Lifecycle, Inspection & Warehouse
      'status_under_inspection': 'Under Inspection',
      'status_quality_verified': 'Quality Verified',
      'status_sold_warehouse': 'Sold to Warehouse',
      'filter_verified': 'Quality Verified',
      'filter_inspection': 'Under Inspection',
      'filter_sold': 'Sold to Warehouse',
      'inspection_report': 'Quality Inspection Report',
      'inspection_cert_title': 'Official Quality Grading Certificate',
      'moisture_level': 'Moisture Level',
      'purity_rate': 'Crop Purity',
      'foreign_matter': 'Foreign Matter',
      'assigned_grade': 'Assigned Grade',
      'assessed_price': 'Assessed Mandi Rate',
      'inspector_name': 'Inspecting Officer',
      'lab_cert_no': 'Lab Certificate No',
      'price_pending_inspection': 'Pending Inspection',
      'quality_valuation_note': 'Quality-based Mandi Valuation: The field quality inspection team will inspect your harvest, test moisture & purity, and assign the official graded price based on APMC/MSP rates.',
      'submit_for_inspection': 'Submit for Quality Inspection',
      'view_inspection_report': 'View Quality Certificate',
      'sell_to_warehouse': 'Sell to Warehouse',
      'warehouse_procurement': 'Warehouse Procurement',
      'select_warehouse': 'Select Authorized Warehouse',
      'quantity_to_sell': 'Quantity to Sell',
      'transport_method': 'Transport / Dispatch Mode',
      'warehouse_pickup': 'Warehouse Logistics Pickup (Truck)',
      'farmer_self_drop': 'Self-Dispatch to Godown Yard',
      'confirm_warehouse_sale': 'Confirm Warehouse Sale & Generate e-NWR',
      'enwr_receipt': 'Electronic Negotiable Warehouse Receipt (e-NWR)',
      'warehouse_sale_success': 'Produce Sold to Warehouse!',
      'payout_credited_note': 'Payment escrow initiated & credited to your Kisan Wallet.',
      'farm_pickup_location': 'Farm Pickup Location',
      'harvest_date': 'Harvest Date',
      'warehouse_orders_title': 'Warehouse Purchase Orders',
      'incoming_warehouse_orders': 'Incoming Warehouse Orders',
      'locked_assessed_rate': 'Locked to Assessed QC Rate',
      'accept_warehouse_order': 'Accept Warehouse Order & Sell',
      'warehouse_po_number': 'Purchase Order ID',
      'warehouse_orders_notice': 'This verified lot can only be sold against official Purchase Orders issued by accredited warehouses at the certified quality rate.',
      'orders_available': 'Orders Available',
      'orders_received_count': 'Orders Received',
      'filter_warehouse_orders': 'Warehouse Orders',
      'warehouse_badge_order': 'Warehouse PO',
      'govt_accredited': 'Govt Accredited',
      'locked_qc_price': 'Locked QC Rate',
      'view_details_btn': 'View Details',
      'review_warehouse_orders': 'Review & Accept Warehouse Orders (3)',
    },
    'hi': {
      // Nav & Common
      'nav_home': 'होम',
      'nav_products': 'मेरे उत्पाद',
      'nav_orders': 'ऑर्डर्स',
      'nav_wallet': 'वॉलेट',
      'nav_profile': 'प्रोफाइल',
      'app_title': 'किसान साथी',

      // Units
      'unit_kg': 'किग्रा',
      'unit_qtl': 'क्विंटल',
      'unit_ton': 'टन',
      'unit_acres': 'एकड़',

      // Farmer Persona & Locations
      'farmer_name': 'रामेश्वर सिंह',
      'default_location': 'सीहोर, मध्य प्रदेश',
      'location_sehore': 'सीहोर, मध्य प्रदेश',
      'location_mp': 'मध्य प्रदेश',

      // Farm Details & Insurance
      'kharif_rabi_badge': 'खरीफ और रबी',
      'val_registered_land': '4.5 एकड़ (काली मिट्टी)',
      'val_kcc_limit': 'सक्रिय (सीमा ₹3,00,000)',
      'val_crop_insurance': 'बीमाकृत (रबी 2026)',
      'val_primary_crops': 'गेहूं, सोयाबीन, टमाटर',
      'val_bank_sbi': 'भारतीय स्टेट बैंक (SBI)',
      'val_aadhaar_status': 'UIDAI द्वारा सत्यापित',
      'val_total_land_loc': '4.5 एकड़ (सीहोर)',
      'val_pm_kisan_status': 'लिंक्ड और सक्रिय',
      'val_village': 'आष्टा ग्राम, सीहोर',
      'val_district_state': 'सीहोर, म.प्र. - 466116',
      'val_nearest_mandi': 'सीहोर कृषि उपज मंडी (4 किमी)',

      // Categories
      'category_grains': 'अनाज (Grains)',
      'category_fruits': 'फल (Fruits)',
      'category_vegetables': 'सब्जियाँ (Vegetables)',
      'category_pulses': 'दालें (Pulses)',
      'category_pulses_lentils': 'दालें और दलहन (Pulses & Lentils)',
      'category_oilseeds': 'तिलहन (Oilseeds)',
      'category_spices': 'मसाले (Spices)',
      'category_organic': 'जैविक उत्पाद (Organic)',

      'Grains': 'अनाज (Grains)',
      'Fruits': 'फल (Fruits)',
      'Vegetables': 'सब्जियाँ (Vegetables)',
      'Pulses': 'दालें (Pulses)',
      'Pulses & Lentils': 'दालें और दलहन',
      'Oilseeds': 'तिलहन',
      'Spices': 'मसाले',
      'Organic Produce': 'जैविक उत्पाद',

      // Specific Crops & Produce
      'Wheat (Local Quality)': 'गेहूं (देसी क्वालिटी)',
      'Sharbati Wheat': 'शरबती गेहूं',
      'Wheat': 'गेहूं',
      'Tomatoes': 'टमाटर (Tomatoes)',
      'Fresh Tomatoes': 'ताजा टमाटर',
      'Potatoes': 'आलू (Potatoes)',
      'Chana Dal': 'चना दाल (Chana Dal)',
      'Desi Chickpeas': 'देसी चना',
      'Yellow Soyabean': 'पीली सोयाबीन',
      'Soyabean': 'सोयाबीन',
      'Mustard Seeds': 'सरसों / राई',
      'Fresh Apples': 'ताजे सेब',
      'Apples': 'सेब',
      'Onions': 'प्याज',
      'Rice (Basmati)': 'चावल (बासमती)',
      'Rice': 'चावल',
      'Cotton (Kapas)': 'कपास (रुई)',
      'Garlic': 'लहसुन',
      'Ginger': 'अदरक',

      // Buyers
      'buyer_ramesh_kirana': 'रमेश किराना स्टोर, इंदौर',
      'buyer_shri_shyam': 'श्री श्याम ट्रेडर्स, भोपाल',
      'buyer_krishi_mandi': 'कृषि मंडी, उज्जैन',
      'buyer_sahyadri_fpo': 'सह्याद्री फार्मर्स प्रोड्यूसर कं.',

      // Home Screen
      'greeting': 'नमस्ते किसान!',
      'sell_produce_title': 'अपनी उपज बेचें',
      'sell_produce_sub': 'सीधे खरीदारों को',
      'add_product_btn': 'उत्पाद जोड़ें',
      'total_products': 'कुल उत्पाद',
      'total_orders': 'कुल ऑर्डर्स',
      'total_sales': 'कुल बिक्री',
      'today_overview': 'आज का विवरण',
      'new_orders': 'नए ऑर्डर्स',
      'in_processing': 'प्रक्रिया में',
      'completed': 'पूर्ण',
      'live_mandi_rates': 'लाइव मंडी भाव',
      'view_all': 'सभी देखें',
      'live_badge': 'लाइव',

      // Profile Screen
      'my_profile': 'मेरा प्रोफाइल',
      'personal_info': 'व्यक्तिगत जानकारी',
      'bank_details': 'बैंक विवरण',
      'address_farm_loc': 'पता और खेत का स्थान',
      'sales_mandi_reports': 'बिक्री और मंडी रिपोर्ट',
      'language': 'भाषा',
      'help_support': 'सहायता और समर्थन',
      'log_out': 'लॉग आउट',
      'logout_confirm_title': 'लॉग आउट करें?',
      'logout_confirm_desc': 'क्या आप अपने किसान साथी खाते से लॉग आउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'agri_land_insurance': 'कृषि भूमि और फसल बीमा',
      'registered_land': 'पंजीकृत भूमि धारिता',
      'kcc': 'किसान क्रेडिट कार्ड (KCC)',
      'crop_insurance': 'प्रधानमंत्री फसल बीमा',
      'primary_crops': 'मुख्य फसलें',
      'govt_footer_1': 'किसान साथी ऐप v2.4.0 • भारत सरकार कृषि पोर्टल',
      'govt_footer_2': 'आधार e-KYC और डीबीटी सुरक्षित भुगतान 🔒',
      'select_language': 'भाषा चुनें',
      'update_profile_photo': 'प्रोफ़ाइल फ़ोटो बदलें',
      'take_camera_photo': 'कैमरा से फोटो लें',
      'choose_gallery': 'गैलरी से चुनें',
      'detect_gps_btn': 'लाइव खेत GPS लोकेशन प्राप्त करें',
      'tap_to_call': 'कॉल करने के लिए टैप करें',

      // My Products Screen
      'my_products_title': 'मेरे उत्पाद',
      'inventory_overview': 'स्टॉक विवरण',
      'listed_produce': 'सूचीबद्ध फसलें',
      'active_stock': 'सक्रिय स्टॉक',
      'total_worth': 'कुल मूल्यांकन',
      'items_count': 'फसलें',
      'crops_count': 'फसलें',
      'all_filter': 'सभी',
      'active_filter': 'सक्रिय',
      'inactive_filter': 'निष्क्रिय',
      'grade_a': 'ग्रेड ए',
      'grade_standard': 'मानक',
      'grade_organic': 'जैविक',
      'status_active': 'सक्रिय',
      'status_inactive': 'निष्क्रिय',
      'total_prefix': 'कुल:',

      // Orders Screen
      'my_orders_title': 'मेरे ऑर्डर्स',
      'filter_all': 'सभी',
      'filter_new': 'नए',
      'filter_processing': 'प्रक्रिया में',
      'filter_completed': 'पूर्ण',
      'order_id': 'ऑर्डर आईडी',
      'view_details': 'विवरण देखें',
      'order_details': 'ऑर्डर विवरण',
      'buyer_info': 'खरीदार की जानकारी',
      'product_details': 'उत्पाद विवरण',
      'order_timeline': 'ऑर्डर स्थिति टाइमलाइन',
      'accept_order': 'ऑर्डर स्वीकार करें',
      'decline_order': 'अस्वीकार करें',
      'order_accepted_splash_title': 'ऑर्डर स्वीकार किया गया!',
      'order_accepted_splash_subtitle': 'डिलीवरी के लिए पैकिंग शुरू हो गई है। अपनी उपज तैयार करें।',
      'packaging_in_progress': 'डिलीवरी के लिए पैकिंग जारी है',
      'order_delivered_splash_title': 'डिलीवरी पूर्ण हुई!',
      'order_delivered_splash_subtitle': 'ऑर्डर खरीदार को सफलतापूर्वक डिलीवर कर दिया गया! राशि आपके वॉलेट में जमा कर दी गई है।',
      'payment_credited_to_wallet': 'वॉलेट में भुगतान जमा हुआ',
      'continue_to_orders': 'मेरे ऑर्डर्स पर वापस जाएं',
      'view_order_details': 'ऑर्डर विवरण देखें',
      'order_splash_done': 'पूर्ण',

      // Wallet Screen
      'my_wallet': 'मेरा वॉलेट',
      'total_balance': 'कुल शेष राशि',
      'withdraw_btn': 'बैंक में निकालें',
      'earned_this_month': 'इस महीने की कमाई',
      'withdrawn': 'निकाली गई राशि',
      'transfer_fee': 'तत्काल IMPS (शून्य शुल्क)',
      'recent_transactions': 'हाल के लेन-देन',
      'linked_bank': 'लिंक्ड बैंक खाता (DBT सत्यापित)',
      'linked_bank_accounts': 'लिंक्ड बैंक खाते',
      'add_bank_account': 'बैंक खाता जोड़ें',
      'account_holder_name': 'खाताधारक का नाम',
      'select_bank': 'बैंक चुनें',
      'account_number': 'खाता संख्या',
      'confirm_account_number': 'खाता संख्या पुनः दर्ज करें',
      'ifsc_code': 'IFSC कोड',
      'account_type': 'खाता प्रकार',
      'verify_and_link': 'सत्यापित करें और जोड़ें',
      'view_sales_analytics': 'बिक्री और मंडी विश्लेषण देखें',

      // Add Product Screen
      'add_new_product': 'नया उत्पाद जोड़ें',
      'crop_photo': 'फसल की फोटो',
      'product_name': 'उत्पाद का नाम',
      'category': 'श्रेणी',
      'quality_grade': 'गुणवत्ता ग्रेड',
      'description_optional': 'विवरण (वैकल्पिक)',
      'publish_product': 'मंडी में प्रकाशित करें',

      // Produce Lifecycle, Inspection & Warehouse
      'status_under_inspection': 'निरीक्षण में',
      'status_quality_verified': 'गुणवत्ता सत्यापित',
      'status_sold_warehouse': 'गोदाम में विक्रय',
      'filter_verified': 'गुणवत्ता सत्यापित',
      'filter_inspection': 'निरीक्षण में',
      'filter_sold': 'गोदाम विक्रय',
      'inspection_report': 'गुणवत्ता निरीक्षण रिपोर्ट',
      'inspection_cert_title': 'आधिकारिक गुणवत्ता प्रमाण पत्र',
      'moisture_level': 'नमी का स्तर',
      'purity_rate': 'फसल शुद्धता',
      'foreign_matter': 'कचरा / विदेशी तत्व',
      'assigned_grade': 'निर्धारित ग्रेड',
      'assessed_price': 'मूल्यांकित मंडी भाव',
      'inspector_name': 'निरीक्षण अधिकारी',
      'lab_cert_no': 'लैब प्रमाण पत्र क्र.',
      'price_pending_inspection': 'निरीक्षण प्रतीक्षारत',
      'quality_valuation_note': 'गुणवत्ता आधारित मूल्यांकन: निरीक्षण टीम नमी और शुद्धता की जांच कर आधिकारिक ग्रेड और भाव निर्धारित करेगी।',
      'submit_for_inspection': 'गुणवत्ता निरीक्षण हेतु सबमिट करें',
      'view_inspection_report': 'गुणवत्ता प्रमाण पत्र देखें',
      'sell_to_warehouse': 'गोदाम को बेचें',
      'warehouse_procurement': 'गोदाम खरीद व भंडारण',
      'select_warehouse': 'अधिकृत गोदाम चुनें',
      'quantity_to_sell': 'बेचने हेतु मात्रा',
      'transport_method': 'परिवहन माध्यम',
      'warehouse_pickup': 'गोदाम पिकअप ट्रक',
      'farmer_self_drop': 'स्वयं गोदाम में पहुंचाएं',
      'confirm_warehouse_sale': 'गोदाम बिक्री पुष्टि करें (e-NWR)',
      'enwr_receipt': 'इलेक्ट्रॉनिक वेयरहाउस रसीद (e-NWR)',
      'warehouse_sale_success': 'गोदाम में फसल सफलतापूर्वक बिकी!',
      'payout_credited_note': 'भुगतान आपके किसान वॉलेट में जमा कर दिया गया है।',
      'farm_pickup_location': 'खेत का पिकअप स्थान',
      'harvest_date': 'फसल कटाई की तारीख',
      'warehouse_orders_title': 'वेयरहाउस खरीद आदेश',
      'incoming_warehouse_orders': 'प्राप्त वेयरहाउस खरीद आदेश',
      'locked_assessed_rate': 'प्रमाणित गुणवत्ता भाव (फिक्स्ड)',
      'accept_warehouse_order': 'वेयरहाउस आदेश स्वीकारें और बेचें',
      'warehouse_po_number': 'खरीद आदेश क्र. (PO ID)',
      'warehouse_orders_notice': 'यह सत्यापित फसल केवल अधिकृत वेयरहाउसों द्वारा जारी खरीद आदेशों पर ही प्रमाणित गुणवत्ता दर पर बेची जा सकती है।',
      'orders_available': 'आदेश उपलब्ध',
      'orders_received_count': 'आदेश प्राप्त',
      'filter_warehouse_orders': 'वेयरहाउस ऑर्डर्स',
      'warehouse_badge_order': 'वेयरहाउस आदेश',
      'govt_accredited': 'सरकारी मान्यता प्राप्त',
      'locked_qc_price': 'प्रमाणित गुणवत्ता दर',
      'view_details_btn': 'विवरण देखें',
      'review_warehouse_orders': 'प्राप्त वेयरहाउस आदेश देखें और स्वीकारें (3)',
    },
    'mr': {
      // Nav & Common
      'nav_home': 'मुख्यपृष्ठ',
      'nav_products': 'माझे उत्पादन',
      'nav_orders': 'ऑर्डर्स',
      'nav_wallet': 'वॉलेट',
      'nav_profile': 'प्रोफाइल',
      'app_title': 'किसान साथी',

      // Units
      'unit_kg': 'किलो',
      'unit_qtl': 'क्विंटल',
      'unit_ton': 'टन',
      'unit_acres': 'एकर',

      // Farmer Persona & Locations
      'farmer_name': 'रामेश्वर सिंग',
      'default_location': 'सिहोर, मध्य प्रदेश',
      'location_sehore': 'सिहोर, मध्य प्रदेश',
      'location_mp': 'मध्य प्रदेश',

      // Farm Details & Insurance
      'kharif_rabi_badge': 'खरीप आणि रब्बी',
      'val_registered_land': '4.5 एकर (काळी माती)',
      'val_kcc_limit': 'सक्रिय (मर्यादा ₹3,00,000)',
      'val_crop_insurance': 'विमा उतरवलेला (रब्बी 2026)',
      'val_primary_crops': 'गहू, सोयाबीन, टोमॅटो',
      'val_bank_sbi': 'स्टेट बँक ऑफ इंडिया (SBI)',
      'val_aadhaar_status': 'UIDAI द्वारे प्रमाणित',
      'val_total_land_loc': '4.5 एकर (सिहोर)',
      'val_pm_kisan_status': 'जोडलेले आणि सक्रिय',
      'val_village': 'आष्टा ग्राम, सिहोर',
      'val_district_state': 'सिहोर, म.प्र. - 466116',
      'val_nearest_mandi': 'सिहोर कृषी उत्पन्न बाजार समिती (4 किमी)',

      // Categories
      'category_grains': 'धान्य (Grains)',
      'category_fruits': 'फळे (Fruits)',
      'category_vegetables': 'भाज्या (Vegetables)',
      'category_pulses': 'डाळी (Pulses)',
      'category_pulses_lentils': 'डाळी आणि कडधान्ये',
      'category_oilseeds': 'गळित धान्ये (Oilseeds)',
      'category_spices': 'मसाले (Spices)',
      'category_organic': 'सेंद्रिय उत्पादने (Organic)',

      'Grains': 'धान्य (Grains)',
      'Fruits': 'फळे (Fruits)',
      'Vegetables': 'भाज्या (Vegetables)',
      'Pulses': 'डाळी (Pulses)',
      'Pulses & Lentils': 'डाळी आणि कडधान्ये',
      'Oilseeds': 'गळित धान्ये',
      'Spices': 'मसाले',
      'Organic Produce': 'सेंद्रिय उत्पादने',

      // Specific Crops & Produce
      'Wheat (Local Quality)': 'गहू (स्थानिक प्रत)',
      'Sharbati Wheat': 'शरबती गहू',
      'Wheat': 'गहू',
      'Tomatoes': 'टोमॅटो (Tomatoes)',
      'Fresh Tomatoes': 'ताजे टोमॅटो',
      'Potatoes': 'बटाटे (Potatoes)',
      'Chana Dal': 'हरभरा डाळ (Chana Dal)',
      'Desi Chickpeas': 'देशी हरभरा',
      'Yellow Soyabean': 'पिवळी सोयाबीन',
      'Soyabean': 'सोयाबीन',
      'Mustard Seeds': 'मोहरी / राई',
      'Fresh Apples': 'ताजी सफरचंद',
      'Apples': 'सफरचंद',
      'Onions': 'कांदा',
      'Rice (Basmati)': 'तांदूळ (बासमती)',
      'Rice': 'तांदूळ',
      'Cotton (Kapas)': 'कापूस',
      'Garlic': 'लसूण',
      'Ginger': 'आले',

      // Buyers
      'buyer_ramesh_kirana': 'रमेश किराणा स्टोअर, इंदूर',
      'buyer_shri_shyam': 'श्री श्याम ट्रेडर्स, भोपाळ',
      'buyer_krishi_mandi': 'कृषी बाजार, उज्जैन',
      'buyer_sahyadri_fpo': 'सह्याद्री फार्मर्स प्रोड्युसर कं.',

      // Home Screen
      'greeting': 'नमस्कार शेतकरी!',
      'sell_produce_title': 'आपला शेतमाल विका',
      'sell_produce_sub': 'थेट खरेदीदारांना',
      'add_product_btn': 'उत्पादन जोडा',
      'total_products': 'एकूण उत्पादने',
      'total_orders': 'एकूण ऑर्डर्स',
      'total_sales': 'एकूण विक्री',
      'today_overview': 'आजचा आढावा',
      'new_orders': 'नवीन ऑर्डर्स',
      'in_processing': 'प्रक्रियेत',
      'completed': 'पूर्ण',
      'live_mandi_rates': 'थेट बाजार भाव',
      'view_all': 'सर्व पहा',
      'live_badge': 'थेट',

      // Profile Screen
      'my_profile': 'माझे प्रोफाइल',
      'personal_info': 'वैयक्तिक माहिती',
      'bank_details': 'बँक तपशील',
      'address_farm_loc': 'पत्ता आणि शेताचे स्थान',
      'sales_mandi_reports': 'विक्री आणि बाजार अहवाल',
      'language': 'भाषा',
      'help_support': 'मदत आणि समर्थन',
      'log_out': 'लॉग आउट',
      'logout_confirm_title': 'लॉग आउट करायचे?',
      'logout_confirm_desc': 'तुम्ही तुमच्या किसान खात्यातून बाहेर पडू इच्छिता का?',
      'cancel': 'रद्द करा',
      'agri_land_insurance': 'शेती जमीन आणि पीक विमा',
      'registered_land': 'नोंदणीकृत जमीन',
      'kcc': 'किसान क्रेडिट कार्ड (KCC)',
      'crop_insurance': 'पंतप्रधान पीक विमा',
      'primary_crops': 'मुख्य पिके',
      'govt_footer_1': 'किसान साथी अॅप v2.4.0 • भारत सरकार कृषी पोर्टल',
      'govt_footer_2': 'आधार e-KYC आणि थेट DBT सुरक्षित 🔒',
      'select_language': 'भाषा निवडा',
      'update_profile_photo': 'प्रोफाइल फोटो बदला',
      'take_camera_photo': 'कॅमेराने फोटो घ्या',
      'choose_gallery': 'गॅलरीतून निवडा',
      'detect_gps_btn': 'थेट शेत GPS स्थान मिळवा',
      'tap_to_call': 'कॉल करण्यासाठी टॅप करा',

      // My Products Screen
      'my_products_title': 'माझे उत्पादन',
      'inventory_overview': 'साठा आढावा',
      'listed_produce': 'नोंदवलेला शेतमाल',
      'active_stock': 'सक्रिय साठा',
      'total_worth': 'एकूण मूल्य',
      'items_count': 'पिके',
      'crops_count': 'पिके',
      'all_filter': 'सर्व',
      'active_filter': 'सक्रिय',
      'inactive_filter': 'निष्क्रिय',
      'grade_a': 'ग्रेड ए',
      'grade_standard': 'प्रमाणित',
      'grade_organic': 'सेंद्रिय',
      'status_active': 'सक्रिय',
      'status_inactive': 'निष्क्रिय',
      'total_prefix': 'एकूण:',

      // Orders Screen
      'my_orders_title': 'माझे ऑर्डर्स',
      'filter_all': 'सर्व',
      'filter_new': 'नवीन',
      'filter_processing': 'प्रक्रियेत',
      'filter_completed': 'पूर्ण',
      'order_id': 'ऑर्डर आयडी',
      'view_details': 'तपशील पहा',
      'order_details': 'ऑर्डर तपशील',
      'buyer_info': 'खरेदीदाराची माहिती',
      'product_details': 'उत्पादन तपशील',
      'order_timeline': 'ऑर्डर प्रगती वेळ',
      'accept_order': 'ऑर्डर स्वीकारा',
      'decline_order': 'नकारा',
      'order_accepted_splash_title': 'ऑर्डर स्वीकारण्यात आला!',
      'order_accepted_splash_subtitle': 'डिलिव्हरीसाठी पॅकिंग सुरू झाले आहे. तुमचे उत्पादन तयार करा.',
      'packaging_in_progress': 'डिलिव्हरीसाठी पॅकिंग प्रक्रियेत आहे',
      'order_delivered_splash_title': 'डिलिव्हरी पूर्ण झाली!',
      'order_delivered_splash_subtitle': 'ऑर्डर यशस्वीरित्या वितरित केली गेली आहे! रक्कम तुमच्या वॉलेटमध्ये जमा झाली आहे.',
      'payment_credited_to_wallet': 'वॉलेटमध्ये पेमेंट जमा झाले',
      'continue_to_orders': 'माझ्या ऑर्डर्सवर परत जा',
      'view_order_details': 'ऑर्डर तपशील पहा',
      'order_splash_done': 'झाले',

      // Wallet Screen
      'my_wallet': 'माझे वॉलेट',
      'total_balance': 'एकूण शिल्लक',
      'withdraw_btn': 'बँकेत काढा',
      'earned_this_month': 'या महिन्याची कमाई',
      'withdrawn': 'काढलेली रक्कम',
      'transfer_fee': 'झटपट IMPS (विनाशुल्क)',
      'recent_transactions': 'अलीकडील व्यवहार',
      'linked_bank': 'जोडलेले बँक खाते (DBT प्रमाणित)',
      'linked_bank_accounts': 'जोडलेली बँक खाती',
      'add_bank_account': 'बँक खाते जोडा',
      'account_holder_name': 'खातेदाराचे नाव',
      'select_bank': 'बँक निवडा',
      'account_number': 'खाते क्रमांक',
      'confirm_account_number': 'खाते क्रमांक पुन्हा प्रविष्ट करा',
      'ifsc_code': 'IFSC कोड',
      'account_type': 'खात्याचा प्रकार',
      'verify_and_link': 'प्रमाणित करा आणि जोडा',
      'view_sales_analytics': 'विक्री आणि बाजार विश्लेषण पहा',

      // Add Product Screen
      'add_new_product': 'नवीन उत्पादन जोडा',
      'crop_photo': 'पिकाचा फोटो',
      'product_name': 'उत्पादनाचे नाव',
      'category': 'श्रेणी',
      'quality_grade': 'गुणवत्ता प्रत',
      'description_optional': 'वर्णन (पर्यायी)',
      'publish_product': 'बाजारात प्रकाशित करा',

      // Produce Lifecycle, Inspection & Warehouse
      'status_under_inspection': 'तपासणीत',
      'status_quality_verified': 'गुणवत्ता प्रमाणित',
      'status_sold_warehouse': 'गोदामात विक्री',
      'filter_verified': 'गुणवत्ता प्रमाणित',
      'filter_inspection': 'तपासणीत',
      'filter_sold': 'गोदाम विक्री',
      'inspection_report': 'गुणवत्ता तपासणी अहवाल',
      'inspection_cert_title': 'अधिकृत गुणवत्ता प्रमाणपत्र',
      'moisture_level': 'ओलाव्याची पातळी',
      'purity_rate': 'पीक शुद्धता',
      'foreign_matter': 'कचरा / बाह्य घटक',
      'assigned_grade': 'ठरवलेली प्रत',
      'assessed_price': 'अंदाजित बाजार भाव',
      'inspector_name': 'तपासणी अधिकारी',
      'lab_cert_no': 'प्रयोगशाळा प्रमाणपत्र क्र.',
      'price_pending_inspection': 'तपासणी प्रलंबित',
      'quality_valuation_note': 'गुणवत्ता आधारित मूल्यांकन: तपासणी पथक ओलावा व शुद्धता तपासून अधिकृत प्रत व दर निश्चित करेल.',
      'submit_for_inspection': 'गुणवत्ता तपासणीसाठी सबमिट करा',
      'view_inspection_report': 'गुणवत्ता प्रमाणपत्र पहा',
      'sell_to_warehouse': 'गोदामाला विका',
      'warehouse_procurement': 'गोदाम खरेदी आणि साठवणूक',
      'select_warehouse': 'अधिकृत गोदाम निवडा',
      'quantity_to_sell': 'विकायची मात्रा',
      'transport_method': 'वाहतूक पद्धत',
      'warehouse_pickup': 'गोदाम पिकअप ट्रक',
      'farmer_self_drop': 'स्वतः गोदामात पोहचवा',
      'confirm_warehouse_sale': 'गोदाम विक्री पुष्टी करा (e-NWR)',
      'enwr_receipt': 'इलेक्ट्रॉनिक वेअरहाऊस पावती (e-NWR)',
      'warehouse_sale_success': 'गोदामात माल यशस्वीरित्या विकला गेला!',
      'payout_credited_note': 'पेमेंट तुमच्या किसान वॉलेटमध्ये जमा झाले आहे.',
      'farm_pickup_location': 'शेतातील पिकअप ठिकाण',
      'harvest_date': 'पीक काढणीची तारीख',
      'warehouse_orders_title': 'गोदाम खरेदी आदेश',
      'incoming_warehouse_orders': 'आलेले गोदाम खरेदी आदेश',
      'locked_assessed_rate': 'प्रमाणित गुणवत्ता दर (निश्चित)',
      'accept_warehouse_order': 'गोदाम आदेश स्वीकारा आणि विका',
      'warehouse_po_number': 'खरेदी आदेश क्र. (PO ID)',
      'warehouse_orders_notice': 'हा प्रमाणित माल केवळ अधिकृत गोदामांनी जारी केलेल्या खरेदी आदेशांवरच प्रमाणित दराने विकला जाऊ शकतो.',
      'orders_available': 'आदेश उपलब्ध',
      'orders_received_count': 'आदेश प्राप्त',
      'filter_warehouse_orders': 'गोदाम ऑर्डर्स',
      'warehouse_badge_order': 'गोदाम खरेदी आदेश',
      'govt_accredited': 'शासकीय मान्यताप्राप्त',
      'locked_qc_price': 'प्रमाणित गुणवत्ता दर',
      'view_details_btn': 'तपशील पहा',
      'review_warehouse_orders': 'प्राप्त गोदाम आदेश पहा व स्वीकारा (3)',
    },
    'gu': {
      // Nav & Common
      'nav_home': 'હોમ',
      'nav_products': 'મારા ઉત્પાદનો',
      'nav_orders': 'ઓર્ડર્સ',
      'nav_wallet': 'વોલેટ',
      'nav_profile': 'પ્રોફાઇલ',
      'app_title': 'કિસાન સાથી',

      // Units
      'unit_kg': 'કિગ્રા',
      'unit_qtl': 'ક્વિન્ટલ',
      'unit_ton': 'ટન',
      'unit_acres': 'એકર',

      // Farmer Persona & Locations
      'farmer_name': 'રામેશ્વર સિંહ',
      'default_location': 'સિહોર, મધ્યપ્રદેશ',
      'location_sehore': 'સિહોર, મધ્યપ્રદેશ',
      'location_mp': 'મધ્યપ્રદેશ',

      // Farm Details & Insurance
      'kharif_rabi_badge': 'ખરીફ અને રવિ',
      'val_registered_land': '4.5 એકર (કાળી માટી)',
      'val_kcc_limit': 'સક્રિય (મર્યાદા ₹3,00,000)',
      'val_crop_insurance': 'વીમાધારક (રવિ 2026)',
      'val_primary_crops': 'ઘઉં, સોયાબીન, ટામેટાં',
      'val_bank_sbi': 'સ્ટેટ બેંક ઓફ ઇન્ડિયા (SBI)',
      'val_aadhaar_status': 'UIDAI દ્વારા ચકાસાયેલ',
      'val_total_land_loc': '4.5 એકર (સિહોર)',
      'val_pm_kisan_status': 'લિંક થયેલ અને સક્રિય',
      'val_village': 'આષ્ટા ગામ, સિહોર',
      'val_district_state': 'સિહોર, મ.પ્ર. - 466116',
      'val_nearest_mandi': 'સિહોર મુખ્ય એપીએમસી યાર્ડ (4 કિમી)',

      // Categories
      'category_grains': 'અનાજ (Grains)',
      'category_fruits': 'ફળો (Fruits)',
      'category_vegetables': 'શાકભાજી (Vegetables)',
      'category_pulses': 'કઠોળ (Pulses)',
      'category_pulses_lentils': 'કઠોળ અને દાળ',
      'category_oilseeds': 'તેલીબિયાં (Oilseeds)',
      'category_spices': 'મરી-મસાલા (Spices)',
      'category_organic': 'જૈવિક ઉત્પાદનો (Organic)',

      'Grains': 'અનાજ (Grains)',
      'Fruits': 'ફળો (Fruits)',
      'Vegetables': 'શાકભાજી (Vegetables)',
      'Pulses': 'કઠોળ (Pulses)',
      'Pulses & Lentils': 'કઠોળ અને દાળ',
      'Oilseeds': 'તેલીબિયાં',
      'Spices': 'મરી-મસાલા',
      'Organic Produce': 'જૈવિક ઉત્પાદનો',

      // Specific Crops & Produce
      'Wheat (Local Quality)': 'ઘઉં (સ્થાનિક ગુણવત્તા)',
      'Sharbati Wheat': 'શરબતી ઘઉં',
      'Wheat': 'ઘઉં',
      'Tomatoes': 'ટામેટાં (Tomatoes)',
      'Fresh Tomatoes': 'તાજા ટામેટાં',
      'Potatoes': 'બટાકા (Potatoes)',
      'Chana Dal': 'ચણા દાળ (Chana Dal)',
      'Desi Chickpeas': 'દેશી ચણા',
      'Yellow Soyabean': 'પીળી સોયાબીન',
      'Soyabean': 'સોયાબીન',
      'Mustard Seeds': 'રાઈ / સરસવ',
      'Fresh Apples': 'તાજા સફરજન',
      'Apples': 'સફરજન',
      'Onions': 'ડુંગળી',
      'Rice (Basmati)': 'ચોખા (બાસમતી)',
      'Rice': 'ચોખા',
      'Cotton (Kapas)': 'કપાસ',
      'Garlic': 'લસણ',
      'Ginger': 'આદુ',

      // Buyers
      'buyer_ramesh_kirana': 'રમેશ કિરાણા સ્ટોર, ઇન્દોર',
      'buyer_shri_shyam': 'શ્રી શ્યામ ટ્રેડર્સ, ભોપાલ',
      'buyer_krishi_mandi': 'કૃષિ માર્કેટ, ઉજ્જૈન',
      'buyer_sahyadri_fpo': 'સહ્યાદ્રી ફાર્મર્સ પ્રોડ્યુસર કું.',

      // Home Screen
      'greeting': 'નમસ્તે ખેડૂત!',
      'sell_produce_title': 'તમારો પાક વેચો',
      'sell_produce_sub': 'સીધા ખરીદદારોને',
      'add_product_btn': 'ઉત્પાદન ઉમેરો',
      'total_products': 'કુલ ઉત્પાદનો',
      'total_orders': 'કુલ ઓર્ડર',
      'total_sales': 'કુલ વેચાણ',
      'today_overview': 'આજનો અહેવાલ',
      'new_orders': 'નવા ઓર્ડર્સ',
      'in_processing': 'પ્રક્રિયામાં',
      'completed': 'પૂર્ણ',
      'live_mandi_rates': 'લાઇવ માર્કેટ ભાવ',
      'view_all': 'બધું જુઓ',
      'live_badge': 'લાઇવ',

      // Profile Screen
      'my_profile': 'મારી પ્રોફાઇલ',
      'personal_info': 'વ્યક્તિગત માહિતી',
      'bank_details': 'બેંક વિગતો',
      'address_farm_loc': 'સરનામું અને ખેતરનું સ્થાન',
      'sales_mandi_reports': 'વેચાણ અને માર્કેટ અહેવાલ',
      'language': 'ભાષા',
      'help_support': 'મદદ અને સમર્થન',
      'log_out': 'લૉગ આઉટ',
      'logout_confirm_title': 'લૉગ આઉટ કરવું છે?',
      'logout_confirm_desc': 'શું તમે તમારા કિસાન ખાતામાંથી બહાર નીકળવા માંગો છો?',
      'cancel': 'રદ કરો',
      'agri_land_insurance': 'ખેતીની જમીન અને પાક વીમો',
      'registered_land': 'નોંધાયેલ જમીન',
      'kcc': 'કિસાન ક્રેડિટ કાર્ડ (KCC)',
      'crop_insurance': 'પ્રધાનમંત્રી પાક વીમો',
      'primary_crops': 'મુખ્ય પાક',
      'govt_footer_1': 'કિસાન સાથી એપ v2.4.0 • ભારત સરકાર કૃષિ પોર્ટલ',
      'govt_footer_2': 'આધાર e-KYC અને ડાયરેક્ટ DBT સુરક્ષિત 🔒',
      'select_language': 'ભાષા પસંદ કરો',
      'update_profile_photo': 'પ્રોફાઇલ ફોટો બદલો',
      'take_camera_photo': 'કેમેરાથી ફોટો લો',
      'choose_gallery': 'ગેલેરીમાંથી પસંદ કરો',
      'detect_gps_btn': 'લાઇવ ખેતર GPS લોકેશન મેળવો',
      'tap_to_call': 'કોલ કરવા માટે ટેપ કરો',

      // My Products Screen
      'my_products_title': 'મારા ઉત્પાદનો',
      'inventory_overview': 'સ્ટોક અહેવાલ',
      'listed_produce': 'નોંધાયેલ પાક',
      'active_stock': 'સક્રિય સ્ટોક',
      'total_worth': 'કુલ મૂલ્ય',
      'items_count': 'પાક',
      'crops_count': 'પાક',
      'all_filter': 'બધા',
      'active_filter': 'સક્રિય',
      'inactive_filter': 'નિષ્ક્રિય',
      'grade_a': 'ગ્રેડ એ',
      'grade_standard': 'પ્રમાણભૂત',
      'grade_organic': 'જૈવિક',
      'status_active': 'સક્રિય',
      'status_inactive': 'નિષ્ક્રિય',
      'total_prefix': 'કુલ:',

      // Orders Screen
      'my_orders_title': 'મારા ઓર્ડર્સ',
      'filter_all': 'બધા',
      'filter_new': 'નવા',
      'filter_processing': 'પ્રક્રિયામાં',
      'filter_completed': 'પૂર્ણ',
      'order_id': 'ઓર્ડર આઈડી',
      'view_details': 'વિગતો જુઓ',
      'order_details': 'ઓર્ડર વિગતો',
      'buyer_info': 'ખરીદદારની માહિતી',
      'product_details': 'ઉત્પાદન વિગતો',
      'order_timeline': 'ઓર્ડર સ્થિતિ સમયરેખા',
      'accept_order': 'ઓર્ડર સ્વીકારો',
      'decline_order': 'અસ્વીકાર કરો',
      'order_accepted_splash_title': 'ઓર્ડર સ્વીકારવામાં આવ્યો!',
      'order_accepted_splash_subtitle': 'ડિલિવરી માટે પેકિંગ શરૂ થઈ ગયું છે. તમારી પેદાશ તૈયાર કરો.',
      'packaging_in_progress': 'ડિલિવરી માટે પેકિંગ પ્રક્રિયામાં છે',
      'order_delivered_splash_title': 'ડિલિવરી પૂર્ણ થઈ!',
      'order_delivered_splash_subtitle': 'ઓર્ડર ખરીદનારને સફળતાપૂર્વક ડિલિવર થઈ ગયો છે! રકમ તમારા વૉલેટમાં જમા થઈ ગઈ છે.',
      'payment_credited_to_wallet': 'વૉલેટમાં ચુકવણી જમા થઈ',
      'continue_to_orders': 'મારા ઓર્ડર્સ પર પાછા જાઓ',
      'view_order_details': 'ઓર્ડર વિગતો જુઓ',
      'order_splash_done': 'પૂર્ણ',

      // Wallet Screen
      'my_wallet': 'મારું વૉલેટ',
      'total_balance': 'કુલ બેલેન્સ',
      'withdraw_btn': 'બેંકમાં ઉપાડો',
      'earned_this_month': 'આ મહિનાની કમાણી',
      'withdrawn': 'ઉપાડેલ રકમ',
      'transfer_fee': 'ઇન્સ્ટન્ટ IMPS (ઝીરો ફી)',
      'recent_transactions': 'તાજેતરના વ્યવહારો',
      'linked_bank': 'લિંક થયેલ બેંક એકાઉન્ટ (DBT ચકાસાયેલ)',
      'linked_bank_accounts': 'લિંક થયેલ બેંક એકાઉન્ટ્સ',
      'add_bank_account': 'બેંક ખાતું ઉમેરો',
      'account_holder_name': 'ખાતાધારકનું નામ',
      'select_bank': 'બેંક પસંદ કરો',
      'account_number': 'ખાતા નંબર',
      'confirm_account_number': 'ખાતા નંબર ફરીથી દાખલ કરો',
      'ifsc_code': 'IFSC કોડ',
      'account_type': 'ખાતાનો પ્રકાર',
      'verify_and_link': 'ચકાસો અને લિંક કરો',
      'view_sales_analytics': 'વેચાણ અને માર્કેટ વિશ્લેષણ જુઓ',

      // Add Product Screen
      'add_new_product': 'નવું ઉત્પાદન ઉમેરો',
      'crop_photo': 'પાકનો ફોટો',
      'product_name': 'ઉત્પાદનનું નામ',
      'category': 'શ્રેણી',
      'quality_grade': 'ગુણવત્તા ગ્રેડ',
      'description_optional': 'વર્ણન (વૈકલ્પિક)',
      'publish_product': 'માર્કેટમાં પ્રકાશિત કરો',

      // Produce Lifecycle, Inspection & Warehouse
      'status_under_inspection': 'તપાસ હેઠળ',
      'status_quality_verified': 'ગુણવત્તા ચકાસાયેલ',
      'status_sold_warehouse': 'વેરહાઉસમાં વેચાયેલ',
      'filter_verified': 'ગુણવત્તા ચકાસાયેલ',
      'filter_inspection': 'તપાસ હેઠળ',
      'filter_sold': 'વેરહાઉસ વેચાણ',
      'inspection_report': 'ગુણવત્તા તપાસ અહેવાલ',
      'inspection_cert_title': 'સત્તાવાર ગુણવત્તા પ્રમાણપત્ર',
      'moisture_level': 'ભેજનું પ્રમાણ',
      'purity_rate': 'પાક શુદ્ધતા',
      'foreign_matter': 'બાહ્ય કચરો',
      'assigned_grade': 'નિયત ગ્રેડ',
      'assessed_price': 'મૂલ્યાંકિત માર્કેટ ભાવ',
      'inspector_name': 'તપાસ અધિકારી',
      'lab_cert_no': 'લેબ પ્રમાણપત્ર નં.',
      'price_pending_inspection': 'તપાસ બાકી',
      'quality_valuation_note': 'ગુણવત્તા આધારિત મૂલ્યાંકન: તપાસ ટીમ ભેજ અને શુદ્ધતા ચકાસીને સત્તાવાર ગ્રેડ અને ભાવ નક્કી કરશે.',
      'submit_for_inspection': 'ગુણવત્તા તપાસ માટે સબમિટ કરો',
      'view_inspection_report': 'ગુણવત્તા પ્રમાણપત્ર જુઓ',
      'sell_to_warehouse': 'વેરહાઉસને વેચો',
      'warehouse_procurement': 'વેરહાઉસ ખરીદી અને સંગ્રહ',
      'select_warehouse': 'અધિકૃત વેરહાઉસ પસંદ કરો',
      'quantity_to_sell': 'વેચવાની માત્રા',
      'transport_method': 'પરિવહન પદ્ધતિ',
      'warehouse_pickup': 'વેરહાઉસ પિકઅપ ટ્રક',
      'farmer_self_drop': 'જાતે વેરહાઉસમાં પહોંચાડો',
      'confirm_warehouse_sale': 'વેરહાઉસ વેચાણ કન્ફર્મ કરો (e-NWR)',
      'enwr_receipt': 'ઇલેક્ટ્રોનિક વેરહાઉસ રસીદ (e-NWR)',
      'warehouse_sale_success': 'વેરહાઉસમાં પાક સફળતાપૂર્વક વેચાયો!',
      'payout_credited_note': 'ચુકવણી તમારા કિસાન વોલેટમાં જમા થઈ ગઈ છે.',
      'farm_pickup_location': 'ખેતર પિકઅપ સ્થળ',
      'harvest_date': 'પાક લણણી તારીખ',
      'warehouse_orders_title': 'વેરહાઉસ ખરીદ ઓર્ડર્સ',
      'incoming_warehouse_orders': 'પ્રાપ્ત વેરહાઉસ ખરીદ ઓર્ડર્સ',
      'locked_assessed_rate': 'પ્રમાણિત ગુણવત્તા ભાવ (નિશ્ચિત)',
      'accept_warehouse_order': 'વેરહાઉસ ઓર્ડર સ્વીકારો અને વેચો',
      'warehouse_po_number': 'ખરીદ ઓર્ડર નં. (PO ID)',
      'warehouse_orders_notice': 'આ પ્રમાણિત પાક માત્ર અધિકૃત વેરહાઉસ દ્વારા જારી કરાયેલ ખરીદ ઓર્ડર પર જ પ્રમાણિત ભાવે વેચી શકાય છે.',
      'orders_available': 'ઓર્ડર્સ ઉપલબ્ધ',
      'orders_received_count': 'ઓર્ડર્સ મળ્યા',
      'filter_warehouse_orders': 'વેરહાઉસ ઓર્ડર્સ',
      'warehouse_badge_order': 'વેરહાઉસ ખરીદ ઓર્ડર',
      'govt_accredited': 'સરકારી માન્યતા પ્રાપ્ત',
      'locked_qc_price': 'પ્રમાણિત ગુણવત્તા ભાવ',
      'view_details_btn': 'વિગતો જુઓ',
      'review_warehouse_orders': 'પ્રાપ્ત વેરહાઉસ ઓર્ડર્સ જુઓ અને સ્વીકારો (3)',
    },
  };
}
